//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public business()
        {
            this.business_contract = new HashSet<business_contract>();
            this.customer = new HashSet<customer>();
            this.executers = new HashSet<executers>();
        }
    
        public long busid { get; set; }
        public string bus_f_name { get; set; }
        public byte bushas_active_account { get; set; }
        public string buslinkweb { get; set; }
        public string busdescr { get; set; }
        public string buscity { get; set; }
        public string busstreet { get; set; }
        public string bushousenum { get; set; }
        public string busphone1 { get; set; }
        public string busphone2 { get; set; }
        public string busmobile1 { get; set; }
        public string busmobile2 { get; set; }
        public string busfax1 { get; set; }
        public string busfax2 { get; set; }
        public string busemail { get; set; }
        public int buscurrent_contract_id { get; set; }
        public string busudf_text1 { get; set; }
        public string busudf_text2 { get; set; }
        public string busudf_text3 { get; set; }
        public string busudf_text4 { get; set; }
        public string busudf_text5 { get; set; }
        public int busudf_integer1 { get; set; }
        public int busudf_integer2 { get; set; }
        public int busudf_integer3 { get; set; }
        public int busudf_integer4 { get; set; }
        public int busudf_integer5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<business_contract> business_contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<executers> executers { get; set; }
    }
}
