//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_contract
    {
        public long bcnbusid { get; set; }
        public long bcnconid { get; set; }
        public byte bcnactive { get; set; }
        public Nullable<System.DateTime> bcnbegindate { get; set; }
        public Nullable<System.DateTime> bcnenddate { get; set; }
        public string bcnnotes { get; set; }
        public string bcnudf_text1 { get; set; }
        public string bcnudf_text2 { get; set; }
        public string bcnudf_text3 { get; set; }
        public string bcnudf_text4 { get; set; }
        public string bcnudf_text5 { get; set; }
        public int bcnudf_integer1 { get; set; }
        public int bcnudf_integer2 { get; set; }
        public int bcnudf_integer3 { get; set; }
        public int bcnudf_integer4 { get; set; }
        public int bcnudf_integer5 { get; set; }
    
        public virtual business business { get; set; }
        public virtual contract contract { get; set; }
    }
}
