//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contract()
        {
            this.business_contract = new HashSet<business_contract>();
        }
    
        public long conid { get; set; }
        public string conname { get; set; }
        public string conshortdescr { get; set; }
        public string conlongdescr { get; set; }
        public int conprice { get; set; }
        public byte conactive { get; set; }
        public Nullable<System.DateTime> concreateday { get; set; }
        public Nullable<System.DateTime> conupdateday { get; set; }
        public Nullable<System.DateTime> conendday { get; set; }
        public string conudf_text1 { get; set; }
        public string conudf_text2 { get; set; }
        public string conudf_text3 { get; set; }
        public string conudf_text4 { get; set; }
        public string conudf_text5 { get; set; }
        public int conudf_integer1 { get; set; }
        public int conudf_integer2 { get; set; }
        public int conudf_integer3 { get; set; }
        public int conudf_integer4 { get; set; }
        public int conudf_integer5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<business_contract> business_contract { get; set; }
    }
}
