//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class executers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public executers()
        {
            this.service_executers = new HashSet<service_executers>();
        }
    
        public long exeid { get; set; }
        public long exebusid { get; set; }
        public string exename { get; set; }
        public string exelastname { get; set; }
        public string execalenar { get; set; }
        public string exeudf_text1 { get; set; }
        public string exeudf_text2 { get; set; }
        public string exeudf_text3 { get; set; }
        public string exeudf_text4 { get; set; }
        public string exeudf_text5 { get; set; }
        public int exeudf_integer1 { get; set; }
        public int exeudf_integer2 { get; set; }
        public int exeudf_integer3 { get; set; }
        public int exeudf_integer4 { get; set; }
        public int exeudf_integer5 { get; set; }
    
        public virtual business business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_executers> service_executers { get; set; }
    }
}
