//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class executers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public executers()
        {
            this.service_executers = new HashSet<service_executers>();
        }
        public long exeid { get; set; }
        public long exebusid { get; set; }
      //  [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
        [DefaultValue("")]
        public string exename { get; set; }
        [DefaultValue("")]
        public string exelastname { get; set; }
        [DefaultValue("")]
        public string execalenar { get; set; }
        [DefaultValue("")]
        public string exeudf_text1 { get; set; }
        [DefaultValue("")]
        public string exeudf_text2 { get; set; }
        [DefaultValue("")]
        public string exeudf_text3 { get; set; }
        [DefaultValue("")]
        public string exeudf_text4 { get; set; }
        public string exeudf_text5 { get; set; }
       
    //    string exeudf_text5

    //    {
     //       get { return exeudf_text5; }
     //       set { exeudf_text5 = value; }
         //   get { return exeudf_text5; }
        //    set { if (value == null) exeudf_text5 = ""; }
       //     set { _myProperty = value; }
            //set
            //{
            //  if (value==null)
            //   {
            //        exeudf_text5 = "";
            //   }
            //}
      //  }
        
        public int exeudf_integer1 { get; set; }
        public int exeudf_integer2 { get; set; }
        public int exeudf_integer3 { get; set; }
        public int exeudf_integer4 { get; set; }
        public int exeudf_integer5 { get; set; }
        
    
        public  business business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_executers> service_executers { get; set; }
    }
}
