//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public long ordid { get; set; }
        public long ordexeid { get; set; }
        public long ordbusid { get; set; }
        public long ordservid { get; set; }
        public long ordcusbusid { get; set; }
        public long ordcusid { get; set; }
        public string ordstatus { get; set; }
        public System.DateTime ordopendate { get; set; }
        public System.TimeSpan ordopentime { get; set; }
        public string ordnotes { get; set; }
        public string ordudf_text1 { get; set; }
        public string ordudf_text2 { get; set; }
        public string ordudf_text3 { get; set; }
        public string ordudf_text4 { get; set; }
        public string ordudf_text5 { get; set; }
        public int ordudf_integer1 { get; set; }
        public int ordudf_integer2 { get; set; }
        public int ordudf_integer3 { get; set; }
        public int ordudf_integer4 { get; set; }
        public int ordudf_integer5 { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
