//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.service_executers = new HashSet<service_executers>();
        }
    
        public long servid { get; set; }
        public string servname { get; set; }
        public int servduration { get; set; }
        public string servdescr { get; set; }
        public string servudf_text1 { get; set; }
        public string servudf_text2 { get; set; }
        public string servudf_text3 { get; set; }
        public string servudf_text4 { get; set; }
        public string servudf_text5 { get; set; }
        public int servudf_integer1 { get; set; }
        public int servudf_integer2 { get; set; }
        public int servudf_integer3 { get; set; }
        public int servudf_integer4 { get; set; }
        public int servudf_integer5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_executers> service_executers { get; set; }
    }
}
