//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tor4Me.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9EED4C_tor4meserverEntities : DbContext
    {
        public DB_9EED4C_tor4meserverEntities()
            : base("name=DB_9EED4C_tor4meserverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<business> business { get; set; }
        public virtual DbSet<business_contract> business_contract { get; set; }
        public virtual DbSet<contract> contract { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<executers> executers { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<service_executers> service_executers { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
